import = [
  "./theme.toml"
]

[env]
term = "xterm-256color"

[font]
size = 14.0
[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"
[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"
[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"
[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[window]
decorations = "None"
padding = { x = 4 }
dynamic_padding = true

