import = [
  "./theme.toml"
]

[env]
term = "xterm-256color"

[font]
size = 18.0
[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"
[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"
[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"
[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[window]
decorations = "None"
padding = { x = 4 }
dynamic_padding = true

# Pulled from the Nordic.nvim theme:
# https://github.com/AlexvZyl/nordic.nvim/blob/main/lua/nordic/colors/nordic.lua
[colors.primary]
background = "#242933"
foreground = "#D8DEE9"
dim_foreground = "#BBC3D4"

[colors.cursor]
text = "#242933"
cursor = "#D8DEE9"

[colors.vi_mode_cursor]
text = "#2E3440"
cursor = "#88C0D0"

[colors.search.matches]
foreground = "#2E3440"
background = "#60728A"

[colors.search.focused_match]
foreground = "#2E3440"
background = "#B1C89D"

[colors.footer_bar]
foreground = "#2E3440"
background = "#60728A"

[colors.hints.start]
foreground = "#2E3440"
background = "#EBCB8B"

[colors.hints.end]
foreground = "#2E3440"
background = "#60728A"

[colors.selection]
background = "#2E3440"
text = "#D8DEE9"

[colors.normal]
black = "#191D24"
blue = "#88C0D0"
cyan = "#8FBCBB"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#D8DEE9"
yellow = "#EBCB8B"

[colors.bright]
black = "#3B4252"
blue = "#88C0D0"
cyan = "#93CCDC"
green = "#B1D196"
magenta = "#C895BF"
red = "#D06F79"
white = "#E5E9F0"
yellow = "#F0D399"

[[colors.indexed_colors]]
index = 16
color = "#D08770"

[[colors.indexed_colors]]
index = 17
color = "#D79784"

