---
- name: Install alacritty
  tags:
    - terminal
    - alacritty
  when: "ansible_facts['distribution'] != 'Archlinux'"
  block:
    - name: Print dependency warning
      ansible.builtin.debug:
        msg: "You'll need to make sure the deps are installed first, check here is they aren't installed: https://github.com/alacritty/alacritty/blob/master/INSTALL.md#dependencies"

    - name: Ensure rust compiler set to stable
      ansible.builtin.command: rust override set stable && rustup update stable

    - name: Checkout alacritty repo
      ansible.builtin.git:
        repo: https://github.com/alacritty/alacritty.git
        dest: ~/tools/

    - name: Build alacritty
      ansible.builtin.command: chdir=~/tools/alacritty cargo build --release

- name: Alacritty config
  tags:
    - terminal
    - alacritty
  block:
    - name: Ensure config dir exists
      ansible.builtin.file:
        path: ~/.config/alacritty
        state: directory

    - name: Pull theme file
      ansible.builtin.get_url:
        url: https://github.com/catppuccin/alacritty/raw/main/catppuccin-mocha.toml
        dest: ~/.config/alacritty

    - name: Symlink config file
      file:
        src: "{{ dotfiles_home }}/alacritty/alacritty.toml"
        dest: "{{ root }}/.config/alacritty/alacritty.toml"
        state: link
