# Pulled from the Nordic.nvim theme:
# https://github.com/AlexvZyl/nordic.nvim/blob/main/lua/nordic/colors/nordic.lua
[colors.primary]
background = "#242933"
foreground = "#D8DEE9"
dim_foreground = "#BBC3D4"
bright_foreground = "#D8DEE9"

[colors.cursor]
text = "#2E3440"
cursor = "#D79784"

[colors.vi_mode_cursor]
text = "#2E3440"
cursor = "#88C0D0"

[colors.search.matches]
foreground = "#2E3440"
background = "#60728A"

[colors.search.focused_match]
foreground = "#2E3440"
background = "#B1C89D"

[colors.footer_bar]
foreground = "#2E3440"
background = "#60728A"

[colors.hints.start]
foreground = "#2E3440"
background = "#EBCB8B"

[colors.hints.end]
foreground = "#2E3440"
background = "#60728A"

[colors.selection]
text = "#2E3440"
background = "#f2d5cf"

[colors.normal]
black = "#242933"
red = "#C5727A"
green = "#B1C89D"
yellow = "#EFD49F"
blue = "#81A1C1"
magenta = "#BE9DB8"
cyan = "#80B3B2"
white = "#BBC3D4"

[colors.bright]
black = "#242933"
red = "#C5727A"
green = "#B1C89D"
yellow = "#EFD49F"
blue = "#81A1C1"
magenta = "#BE9DB8"
cyan = "#80B3B2"
white = "#BBC3D4"

[colors.dim]
black = "#51576d"
red = "#C5727A"
green = "#B1C89D"
yellow = "#EFD49F"
blue = "#81A1C1"
magenta = "#BE9DB8"
cyan = "#80B3B2"
white = "#BBC3D4"

[[colors.indexed_colors]]
index = 16
color = "#CB775D"

[[colors.indexed_colors]]
index = 17
color = "#D79784"

