---
- hosts: localhost
  connection: local
  gather_facts: true
  become: true
  become_user: root
  vars:
    root: "~"
    dotfiles_home: "{{ playbook_dir }}"
  tasks:
    - name: Configure terminal
      include_tasks: terminal/tasks.yml
