---
- name: Install Neovim
  include_tasks: "{{ ansible_distribution }}.yml"

- name: Install Neovim and configs
  vars:
    nvim_url: "https://api.github.com/repos/neovim/neovim"
  tags:
    - nvim
    - programs
  block:
    - name: Ensure tools dir exists
      ansible.builtin.file:
        path: ~/tools/
        state: directory

    - name: Grab latest tarball
      ansible.builtin.unarchive:
        src: https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
        dest: ~/Downloads/
        remote_src: true

    - name: Add nvim to tools folder
      ansible.posix.synchronize:
        src: ~/Downloads/nvim-linux64/
        dest: ~/tools/nvim/

    - name: Ensure config dir exists
      ansible.builtin.file:
        path: "{{ root }}/.config/nvim/"
        state: directory

    - name: Symlink config files
      file:
        src: "{{ dotfiles_home }}/nvim/config"
        dest: "{{ root }}/.config/nvim"
        state: link
        force: true

