local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node
local f = ls.function_node
local c = ls.choice_node
local d = ls.dynamic_node
local sn = ls.snippet_node

return {
  -- Floating window snippet
  s("nvimfloat", {
    t("-- Create a floating window"),
    t({ "", "local buf = vim.api.nvim_create_buf(false, true)" }),
    t({ "", "" }),
    t({ "", "-- Buffer options" }),
    t({ "", "vim.api.nvim_set_option_value('bufhidden', 'wipe', { buf = buf })" }),
    t({ "", "" }),
    t({ "", "-- Get editor dimensions" }),
    t({ "", "local width = vim.api.nvim_get_option_value('columns', {})" }),
    t({ "", "local height = vim.api.nvim_get_option_value('lines', {})" }),
    t({ "", "" }),
    t({ "", "-- Calculate floating window size" }),
    t({ "", "local win_width = math.floor(width * " }),
    i(1, "0.8"),
    t(")"),
    t({ "", "local win_height = math.floor(height * " }),
    i(2, "0.8"),
    t(")"),
    t({ "", "" }),
    t({ "", "-- Calculate position to center the window" }),
    t({ "", "local row = math.floor((height - win_height) / 2)" }),
    t({ "", "local col = math.floor((width - win_width) / 2)" }),
    t({ "", "" }),
    t({ "", "-- Window options" }),
    t({ "", "local opts = {" }),
    t({ "", "  relative = '" }),
    c(3, { t("editor"), t("win"), t("cursor") }),
    t("',"),
    t({ "", "  width = win_width," }),
    t({ "", "  height = win_height," }),
    t({ "", "  row = row," }),
    t({ "", "  col = col," }),
    t({ "", "  style = 'minimal'," }),
    t({ "", "  border = '" }),
    c(4, { t("rounded"), t("single"), t("double"), t("solid"), t("shadow"), t("none") }),
    t("',"),
    t({ "", "  title = '" }),
    i(5, "Title"),
    t("',"),
    t({ "", "  title_pos = '" }),
    c(6, { t("center"), t("left"), t("right") }),
    t("',"),
    t({ "", "}" }),
    t({ "", "" }),
    t({ "", "-- Create the window" }),
    t({ "", "local win = vim.api.nvim_open_win(buf, true, opts)" }),
    t({ "", "" }),
    t({ "", "-- Window options" }),
    t({ "", "vim.api.nvim_set_option_value('winhl', 'Normal:Normal,FloatBorder:FloatBorder', { win = win })" }),
    t({ "", "vim.api.nvim_set_option_value('winblend', " }),
    i(7, "0"),
    t(", { win = win })"),
    t({ "", "" }),
    t({ "", "-- Set buffer content" }),
    t({ "", "vim.api.nvim_buf_set_lines(buf, 0, -1, false, {" }),
    t({ "", "  '" }),
    i(8, "Hello from floating window!"),
    t("',"),
    t({ "", "})" }),
    t({ "", "" }),
    t({ "", "-- Optional: Set up keymaps to close the window" }),
    t({ "", "vim.keymap.set('n', 'q', function()" }),
    t({ "", "  vim.api.nvim_win_close(win, true)" }),
    t({ "", "end, { buffer = buf, noremap = true, silent = true })" }),
    t({ "", "" }),
    t({ "", "vim.keymap.set('n', '<Esc>', function()" }),
    t({ "", "  vim.api.nvim_win_close(win, true)" }),
    t({ "", "end, { buffer = buf, noremap = true, silent = true })" }),
    t({ "", "" }),
    i(0),
  }),

  -- Simpler floating window snippet
  s("nvimfloatsimple", {
    t("local buf = vim.api.nvim_create_buf(false, true)"),
    t({ "", "local win = vim.api.nvim_open_win(buf, true, {" }),
    t({ "", "  relative = 'editor'," }),
    t({ "", "  width = " }),
    i(1, "80"),
    t(","),
    t({ "", "  height = " }),
    i(2, "20"),
    t(","),
    t({ "", "  row = " }),
    i(3, "10"),
    t(","),
    t({ "", "  col = " }),
    i(4, "10"),
    t(","),
    t({ "", "  style = 'minimal'," }),
    t({ "", "  border = 'rounded'," }),
    t({ "", "})" }),
    t({ "", "vim.api.nvim_buf_set_lines(buf, 0, -1, false, { '" }),
    i(5, "Content"),
    t("' })"),
    t({ "", "" }),
    i(0),
  }),

  -- Floating window with auto-centered content
  s("nvimfloatcenter", {
    t("local function create_centered_float(content, width_ratio, height_ratio)"),
    t({ "", "  width_ratio = width_ratio or 0.8" }),
    t({ "", "  height_ratio = height_ratio or 0.8" }),
    t({ "", "" }),
    t({ "", "  local buf = vim.api.nvim_create_buf(false, true)" }),
    t({ "", "  local width = vim.api.nvim_get_option_value('columns', {})" }),
    t({ "", "  local height = vim.api.nvim_get_option_value('lines', {})" }),
    t({ "", "" }),
    t({ "", "  local win_width = math.floor(width * width_ratio)" }),
    t({ "", "  local win_height = math.floor(height * height_ratio)" }),
    t({ "", "  local row = math.floor((height - win_height) / 2)" }),
    t({ "", "  local col = math.floor((width - win_width) / 2)" }),
    t({ "", "" }),
    t({ "", "  local win = vim.api.nvim_open_win(buf, true, {" }),
    t({ "", "    relative = 'editor'," }),
    t({ "", "    width = win_width," }),
    t({ "", "    height = win_height," }),
    t({ "", "    row = row," }),
    t({ "", "    col = col," }),
    t({ "", "    style = 'minimal'," }),
    t({ "", "    border = 'rounded'," }),
    t({ "", "  })" }),
    t({ "", "" }),
    t({ "", "  vim.api.nvim_buf_set_lines(buf, 0, -1, false, content)" }),
    t({ "", "" }),
    t({ "", "  vim.keymap.set('n', 'q', function() vim.api.nvim_win_close(win, true) end," }),
    t({ "", "    { buffer = buf, noremap = true, silent = true })" }),
    t({ "", "" }),
    t({ "", "  return buf, win" }),
    t({ "", "end" }),
    t({ "", "" }),
    t({ "", "create_centered_float({ '" }),
    i(1, "Line 1"),
    t("', '"),
    i(2, "Line 2"),
    t("' }, "),
    i(3, "0.6"),
    t(", "),
    i(4, "0.4"),
    t(")"),
    t({ "", "" }),
    i(0),
  }),
}
