---
- name: Install Arch Packages
  tags:
    - packages
    - arch
  block:
    - name: Pacman upgrade
      ansible.builtin.expect:
        command: sudo pacman -Syu
        responses:
          Question:
            - y

    - name: Read package list
      ansible.builtin.file:
        path: "{{ dotfiles_home }}/system/{{ ansible_facts['distribution'] }}.txt"
        state: present
        register: package_file_content

    - name: Install packages for Arch
      ansible.builtin.command: sudo pacman -S --noconfirm "{{ item }}"
      with_items: "{{ package_file_content.content | split('\n') }}"

