---
- name: Install Arch Packages
  tags:
    - packages
    - arch
  block:
    - name: Read package list
      ansible.builtin.file:
        path: "{{ dotfiles_home }}/system/{{ ansible_facts['distribution'] }}.txt"
        state: present
        register: package_file_content

    - name: Install packages for Arch
      community.general.pacman:
        name: "{{ item }}"
        state: present
      with_items: "{{ package_file_content.content | split('\n') }}"

