return {}
-- return {
--   "TheseusGrey/carpenter.nvim",
--   dev = true,
--   dir = "~/projects/carpenter.nvim",
--   event = { "VeryLazy" },
--   dependencies = {
--     "nvim-treesitter/nvim-treesitter",
--     "nvim-lua/plenary.nvim",
--   },
--   ft = "markdown",
--   opts = {},
-- }
