#!/usr/bin/env bash
source_if_exists () {
    if test -r "$1"; then
        source "$1"
    fi
}

source_if_exists ~/config/.env.sh
source_if_exists ~/config/config.zsh
source_if_exists ~/config/git.zsh
source_if_exists ~/config/aliases.sh
source_if_exists ~/.fzf.zsh
source_if_exists /usr/local/etc/profile.d/z.sh
source_if_exists /opt/homebrew/etc/profile.d/z.sh

