---
- name: Setup zsh config files
  tags:
    - zsh
    - terminal
  block:
    - name: Ensure config directory exists
      ansible.builtin.file:
        dest: "{{ root }}/.config/zsh"
        state: directory

    - name: Ensure file to put machine specific config exists
      ansible.builtin.file:
        path: "{{ root }}/env_specific.sh"
        state: touch
        mode: 777

    - name: Populate env.sh with some defaults
      ansible.builtin.lineinfile:
        path: "{{ root }}/env_specific.sh"
        state: present
        regexp: "^export {{ item.key }}="
        line: "export {{ item.key }}={{ item.value }}"
      with_items:
        - { key: DOTFILES, value: "{{ dotfiles_home }}" }
        - { key: EDITOR, value: nvim }
        
    - name: Symlink zshrc
      ansible.builtin.file:
        src: "{{ dotfiles_home }}/zsh/.zshrc"
        dest: "{{ root }}/.zshrc"
        state: link

    - name: Symlink zshenv
      ansible.builtin.file:
        src: "{{ dotfiles_home }}/zsh/.zshenv"
        dest: "{{ root }}/.zshenv"
        state: link
      
    - name: Find terminal Config
      find:
        paths: "{{ dotfiles_home }}/zsh"
        patterns: "*.sh,*.zsh"
      register: terminal_config

    - name: Symlink terminal config
      ansible.builtin.file:
        src: "{{ item.path }}"
        dest: "{{ root }}/.config/zsh/{{ item.path | split('/') | last }}"
        state: link
      with_items: "{{ terminal_config.files }}"

