---
- name: Setup zsh config files
  tags:
    - zsh
    - terminal
  block:
    - name: Ensure config directory exists
      ansible.builtin.file:
        dest: "{{ root }}/.config/zsh"
        state: directory

    - name: Symlink zshrc
      ansible.builtin.file:
        src: "{{ dotfiles_home }}/zsh/.zshrc"
        dest: "{{ root }}/.zshrc"
        state: link

    - name: Symlink zshenv
      ansible.builtin.file:
        src: "{{ dotfiles_home }}/zsh/.zshenv"
        dest: "{{ root }}/.zshenv"
        state: link
      
    - name: Find terminal Config
      find:
        paths: "{{ dotfiles_home }}/zsh"
        patterns: "*.sh,*.zsh"
      register: terminal_config

    - name: Symlink terminal config
      ansible.builtin.file:
        src: "{{ item.path }}"
        dest: "{{ root }}/.config/zsh/{{ item.path | split('/') | last }}"
        state: link
      with_items: "{{ terminal_config.files }}"

